### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by MaksCreative** [myzhang1029/homebrew-myzhang1029#1]
Good afternoon, I really need audacity for my MacBook air m1! How do I install your version via HomeBrew?

**Comment by MaksCreative** [comment]
When entering the brew install audacity-m1 command, it throws the sha256 mismatch error

**Comment by myzhang1029** [comment]
Hmm, that is strange. I don't even have a checksum defined for audacity-m1. Could you please post your output from your terminal?

Thanks for your attention in this formula.

**Comment by MaksCreative** [comment]
Okay. I'll send tomorrow! Tell me, I just have to enter the command brew install audacity-m1

**Comment by myzhang1029** [comment]
If you have this Tap tapped, then yes. But I guess it would be better to use
```
brew install myzhang1029/myzhang1029/audacity-m1
```

**Comment by MaksCreative** [comment]
I'll try tomorrow, thank you! It's just that I record songs through audacity, and now launching through rozetta causes a big delay

**Comment by MaksCreative** [comment]
Error: audacity-m1: SHA256 mismatch
Expected: beebd47ee4ef49a3d69183b1b3142e2b8c28fe68d6bc37bf8ff8a6f3cde56584
Actual: 92bcf5b68bb67fdc102373b96fd8177cb49320b0b290d89714aa71b5486f3fed
File: /Users/anufrievmaksimanatolevic/Library/Caches/Homebrew/downloads/342cd7a1372a2b64069bf711f50a8c3f219b57c351ad00e967956..
To retry an incomplete download, remove the file above.

**Comment by MaksCreative** [comment]
Sorry for waiting

**Comment by myzhang1029** [comment]
Thanks. That is my problem. There was a change in `gas-preprocessor` and the checksum changed.

**Comment by MaksCreative** [comment]
What do we do?

**Comment by myzhang1029** [comment]
Could you please try again and see if there are more problems?

**Comment by MaksCreative** [comment]
I'm at work right now, I'll try it tonight

**Comment by myzhang1029** [comment]
No worries.

And I forgot to mention, since the app installation script does not link the result to `/Applications`, you may want to run
```
ln -s /opt/homebrew/opt/audacity-m1/Audacity.app ~/Applications
``` 
after installation in order to find the app in Launchpad.

**Comment by MaksCreative** [comment]
Good! Thank you

**Comment by MaksCreative** [comment]
Error: audacity-m1: SHA256 mismatch
Expected: no_check
Actual: a146844a7d2f07cc11a0acbf14f7a75e0bf9e3ab80ab83af240027e211f52841
File: /Users/anufrievmaksimanatolevic/Library/Caches/Homebrew/downloads/c4b882aba8b0cdcb6450fd4dd61b416e225a02a326ad42b8ce76dcaf03399497--audacity-applesilicon-arm64-macos.tar.gz
To retry an incomplete download, remove the file above.

**Comment by MaksCreative** [comment]
up

**Comment by myzhang1029** [comment]
I have pushed the fix but I'll do a local reinstall before further bothering you. Sorry...

**Comment by MaksCreative** [comment]
ok) thanks, bro

**Comment by myzhang1029** [comment]
Ok I suppose it should work now. I apologize for making some edits that were not well tested.

**Comment by MaksCreative** [comment]
No problem, I'll try tomorrow
